version: '3.8'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nexqr_db
      - POSTGRES_USER=nexqr_user
      - POSTGRES_PASSWORD=nexqr_pass

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 nexqr_project.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://nexqr_user:nexqr_pass@db:5432/nexqr_db
      - DEBUG=False
      - ALLOWED_HOSTS=*
    depends_on:
      - db

volumes:
  postgres_data:
