# Generated by Django 6.1.1 on 2026-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicqr',
            name='encrypted_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicqr',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
