# Generated by Django 6.1.1 on 2026-09-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dynamicqr_encrypted_payload_dynamicqr_is_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicqr',
            name='is_artistic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dynamicqr',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
